packages:
  - "apps/sdkwork-aiot-h5"
  - "apps/sdkwork-aiot-h5/packages/*"
  - "apps/sdkwork-aiot-pc"
  - "apps/sdkwork-aiot-pc/packages/*"
  - "apps/sdkwork-aiot-shared"
  - "apps/sdkwork-aiot-shared/packages/*"
  - sdks/sdkwork-aiot-app-sdk/sdkwork-aiot-app-sdk-typescript
  - sdks/sdkwork-aiot-backend-sdk/sdkwork-aiot-backend-sdk-typescript
  - ../sdkwork-core/sdkwork-core-pc-react
  - ../sdkwork-ui/sdkwork-ui-pc-react
  - ../sdkwork-utils/packages/sdkwork-utils-typescript
  - ../sdkwork-drive/sdks/sdkwork-drive-app-sdk/sdkwork-drive-app-sdk-typescript
  - ../sdkwork-app-topology
  - ../sdkwork-iam/sdks/sdkwork-iam-app-sdk/sdkwork-iam-app-sdk-typescript/generated/server-openapi
  - ../sdkwork-sdk-commons/sdkwork-sdk-common-typescript

catalog:
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^6.0.1
  lucide-react: ^1.7.0
  i18next: ^26.1.0
  qrcode: ^1.5.4
  react: ^19.2.4
  react-dom: ^19.2.4
  react-i18next: ^17.0.7
  react-hook-form: ^7.72.1
  typescript: ~6.0.2
  vite: ^8.0.3
  vite-plugin-dts: ^4.5.4
