/** v2 topology client env keys — see specs/topology.spec.json and sdkwork-specs/APP_RUNTIME_TOPOLOGY_NAMING.md */

export const VITE_SDKWORK_AIOT_HOSTING = 'VITE_SDKWORK_AIOT_HOSTING';
export const VITE_SDKWORK_AIOT_APPLICATION_APP_HTTP_URL =
  'VITE_SDKWORK_AIOT_APPLICATION_APP_HTTP_URL';
export const VITE_SDKWORK_AIOT_APPLICATION_ADMIN_HTTP_URL =
  'VITE_SDKWORK_AIOT_APPLICATION_ADMIN_HTTP_URL';
export const VITE_SDKWORK_AIOT_EDGE_DEVICE_INGRESS_HTTP_URL =
  'VITE_SDKWORK_AIOT_EDGE_DEVICE_INGRESS_HTTP_URL';
export const VITE_SDKWORK_AIOT_EDGE_DEVICE_INGRESS_WEBSOCKET_URL =
  'VITE_SDKWORK_AIOT_EDGE_DEVICE_INGRESS_WEBSOCKET_URL';
export const VITE_SDKWORK_AIOT_PLATFORM_API_GATEWAY_HTTP_URL =
  'VITE_SDKWORK_AIOT_PLATFORM_API_GATEWAY_HTTP_URL';
export const VITE_SDKWORK_DRIVE_APP_API_BASE_URL = 'VITE_SDKWORK_DRIVE_APP_API_BASE_URL';

export const DEFAULT_LOCAL_APPLICATION_APP_HTTP_URL = 'http://127.0.0.1:18082';
export const DEFAULT_LOCAL_APPLICATION_ADMIN_HTTP_URL = 'http://127.0.0.1:18081';
export const DEFAULT_LOCAL_EDGE_DEVICE_INGRESS_HTTP_URL = 'http://127.0.0.1:18080';
export const DEFAULT_LOCAL_EDGE_DEVICE_INGRESS_WEBSOCKET_URL = 'ws://127.0.0.1:18080';
export const DEFAULT_LOCAL_PLATFORM_API_GATEWAY_HTTP_URL = 'http://127.0.0.1:3900';
