use std::env;
use std::fs;
use std::path::Path;

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct RouteManifestFile {
    routes: Vec<RouteManifestRoute>,
}

#[derive(Debug, Deserialize)]
struct RouteManifestRoute {
    method: String,
    path: String,
    #[serde(rename = "operationId")]
    operation_id: String,
    tags: Vec<String>,
    auth: RouteManifestAuth,
    #[serde(default)]
    idempotent: bool,
    #[serde(rename = "rateLimitTier", default)]
    rate_limit_tier: Option<String>,
}

#[derive(Debug, Deserialize)]
struct RouteManifestAuth {
    mode: String,
}

fn main() {
    let manifest_path =
        Path::new("../../sdks/_route-manifests/app-api/sdkwork-aiot-app-api.route-manifest.json");
    println!("cargo:rerun-if-changed={}", manifest_path.display());

    let manifest = read_manifest(manifest_path);
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    let generated = Path::new(&out_dir).join("iot_app_http_routes.rs");
    fs::write(&generated, render_rust(&manifest.routes))
        .expect("write generated iot app http routes");
}

fn read_manifest(path: &Path) -> RouteManifestFile {
    let raw = fs::read_to_string(path).unwrap_or_else(|error| {
        panic!("failed to read route manifest {}: {error}", path.display())
    });
    serde_json::from_str(&raw).unwrap_or_else(|error| {
        panic!("failed to parse route manifest {}: {error}", path.display())
    })
}

fn render_rust(routes: &[RouteManifestRoute]) -> String {
    let uses_rate_limit_tier = routes.iter().any(|route| route.rate_limit_tier.is_some());
    let contract_import = if uses_rate_limit_tier {
        "use sdkwork_web_contract::{HttpMethod, HttpRoute, RateLimitTier, RouteAuth};\n\n"
    } else {
        "use sdkwork_web_contract::{HttpMethod, HttpRoute, RouteAuth};\n\n"
    };
    let mut output = format!(
        "// @generated by build.rs from sdks/_route-manifests — do not edit.\n{contract_import}\
pub const IOT_APP_HTTP_ROUTES: &[HttpRoute] = &[\n",
    );
    for route in routes {
        output.push_str(&render_route(route));
    }
    output.push_str("];\n");
    output
}

fn render_route(route: &RouteManifestRoute) -> String {
    let method = match route.method.as_str() {
        "GET" => "HttpMethod::Get",
        "POST" => "HttpMethod::Post",
        "PUT" => "HttpMethod::Put",
        "PATCH" => "HttpMethod::Patch",
        "DELETE" => "HttpMethod::Delete",
        other => panic!("unsupported HTTP method: {other}"),
    };
    let auth = match route.auth.mode.as_str() {
        "public" => "RouteAuth::Public",
        "dual-token" => "RouteAuth::DualToken",
        "api-key" => "RouteAuth::ApiKey",
        other => panic!("unsupported auth mode: {other}"),
    };
    let tag = route.tags.first().map(String::as_str).unwrap_or("iot");
    let mut line = format!(
        "    HttpRoute::new({method}, {:?}, {:?}, {:?}, {auth})",
        route.path, tag, route.operation_id
    );
    if route.idempotent {
        line.push_str(".with_idempotent(true)");
    }
    if let Some(tier) = route.rate_limit_tier.as_deref() {
        line.push_str(&format!(
            ".with_rate_limit_tier({})",
            rate_limit_tier_expr(tier)
        ));
    }
    line.push_str(",\n");
    line
}

fn rate_limit_tier_expr(tier: &str) -> &'static str {
    match tier {
        "authCritical" => "RateLimitTier::AuthCritical",
        "openApiDefault" => "RateLimitTier::OpenApiDefault",
        other => panic!("unsupported rateLimitTier: {other}"),
    }
}
