environment = "production"

[http]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["aiot.sdkwork.com", "aiot-app.sdkwork.com", "aiot-admin.sdkwork.com", "edge.aiot.sdkwork.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "sdkwork.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["aiot.birdcoder.com", "aiot-app.birdcoder.com", "aiot-admin.birdcoder.com", "edge.aiot.birdcoder.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "birdcoder.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["aiot.dtupay.com", "aiot-app.dtupay.com", "aiot-admin.dtupay.com", "edge.aiot.dtupay.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "dtupay.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["aiot.noaper.com", "aiot-app.noaper.com", "aiot-admin.noaper.com", "edge.aiot.noaper.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "noaper.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["aiot.sdkwork.cn", "aiot-app.sdkwork.cn", "aiot-admin.sdkwork.cn", "edge.aiot.sdkwork.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "sdkwork.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["aiot.birdcoder.cn", "aiot-app.birdcoder.cn", "aiot-admin.birdcoder.cn", "edge.aiot.birdcoder.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "birdcoder.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["aiot.dtupay.cn", "aiot-app.dtupay.cn", "aiot-admin.dtupay.cn", "edge.aiot.dtupay.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "dtupay.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["aiot.noaper.cn", "aiot-app.noaper.cn", "aiot-admin.noaper.cn", "edge.aiot.noaper.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "noaper.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["aiot.skubc.com", "aiot-app.skubc.com", "aiot-admin.skubc.com", "edge.aiot.skubc.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "skubc.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["aiot.skubc.cn", "aiot-app.skubc.cn", "aiot-admin.skubc.cn", "edge.aiot.skubc.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "skubc.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["aiot.zowalk.com", "aiot-app.zowalk.com", "aiot-admin.zowalk.com", "edge.aiot.zowalk.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "zowalk.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["aiot.zowalk.cn", "aiot-app.zowalk.cn", "aiot-admin.zowalk.cn", "edge.aiot.zowalk.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "zowalk.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["aiot.offer86.com", "aiot-app.offer86.com", "aiot-admin.offer86.com", "edge.aiot.offer86.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "offer86.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["aiot.offer86.cn", "aiot-app.offer86.cn", "aiot-admin.offer86.cn", "edge.aiot.offer86.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "offer86.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["aiot.86offer.com", "aiot-app.86offer.com", "aiot-admin.86offer.com", "edge.aiot.86offer.com"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "86offer.com"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

[[http.server]]
listen = ["443 ssl", "80"]
serverName = ["aiot.86offer.cn", "aiot-app.86offer.cn", "aiot-admin.86offer.cn", "edge.aiot.86offer.cn"]
include = ["snippets/adaptive-web.named-locations.conf", "snippets/gateway-api-locations.production.conf"]

[http.server.tls]
cert = "86offer.cn"

[[http.server.location]]
match = "/"
include = ["snippets/adaptive-web.dispatch.conf"]

